name: Deploy Resources-at-Scale to Azure
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - 'deploy/large-scale/**'
    - '.github/workflows/deploy-resources-at-scale-to-azure'

jobs:

  deploy_to_americas:
      name: Deploy to Americas
      env:
        AZURE_RESOURCEGROUP_NAME: "promitor-testing-infrastructure-large-scale"
      environment:
        name: Promitor Large Scale (Americas)
      runs-on: ubuntu-latest
      steps:
        # Checkout code
      - uses: actions/checkout@main
        name: Checkout code

          # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file for Americas
      - name: Deploy to Azure (Americas)
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./deploy/large-scale/large-scale-americas.bicep
          deploymentName: large-scale-americas-run-${{ github.run_number }}
          deploymentMode: Complete
          failOnStdErr: false

  deploy_to_apac:
      name: Deploy to APAC
      env:
        AZURE_RESOURCEGROUP_NAME: "promitor-testing-infrastructure-large-scale"
      environment:
        name: Promitor Large Scale (APAC)
      runs-on: ubuntu-latest
      steps:
        # Checkout code
      - uses: actions/checkout@main
        name: Checkout code

          # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file for APAC
      - name: Deploy to Azure (APAC)
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./deploy/large-scale/large-scale-apac.bicep
          deploymentName: large-scale-apac-run-${{ github.run_number }}
          deploymentMode: Complete
          failOnStdErr: false

  deploy_to_europe:
      name: Deploy to Europe
      env:
        AZURE_RESOURCEGROUP_NAME: "promitor-testing-infrastructure-large-scale"
      environment:
        name: Promitor Large Scale (Europe)
      runs-on: ubuntu-latest
      steps:
        # Checkout code
      - uses: actions/checkout@main
        name: Checkout code

          # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file for Europe
      - name: Deploy to Azure (Europe)
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./deploy/large-scale/large-scale-europe.bicep
          deploymentName: large-scale-europe-run-${{ github.run_number }}
          deploymentMode: Complete
          failOnStdErr: false